name: Release on tag push

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
  #workflow_dispatch:

# env:
#   CRATE_NAME: dns-forward-over-tcp
#   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Release - ${{ matrix.platform.os_name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          # - os_name: FreeBSD-x86_64
          #   os: ubuntu-20.04
          #   target: x86_64-unknown-freebsd
          #   bin: dns-forward-over-tcp
          #   name: dns-forward-over-tcp-FreeBSD-x86_64.tar.gz
          #   skip_tests: true
          - os_name: Linux-aarch64
            os: ubuntu-20.04
            target: aarch64-unknown-linux-musl
            bin: dns-forward-over-tcp
            name: dns-forward-over-tcp-Linux-aarch64-musl.tar.gz
          - os_name: Linux-arm
            os: ubuntu-20.04
            target: arm-unknown-linux-musleabi
            bin: dns-forward-over-tcp
            name: dns-forward-over-tcp-Linux-arm-musl.tar.gz
          - os_name: Linux-i686
            os: ubuntu-20.04
            target: i686-unknown-linux-musl
            bin: dns-forward-over-tcp
            name: dns-forward-over-tcp-Linux-i686-musl.tar.gz
            skip_tests: true
          - os_name: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-musl
            bin: dns-forward-over-tcp
            name: dns-forward-over-tcp-Linux-x86_64-musl.tar.gz
          # - os_name: Linux-powerpc
          #   os: ubuntu-20.04
          #   target: powerpc-unknown-linux-gnu
          #   bin: dns-forward-over-tcp
          #   name: dns-forward-over-tcp-Linux-powerpc-gnu.tar.gz
          #   skip_tests: true
          # - os_name: Linux-powerpc64
          #   os: ubuntu-20.04
          #   target: powerpc64-unknown-linux-gnu
          #   bin: dns-forward-over-tcp
          #   name: dns-forward-over-tcp-Linux-powerpc64-gnu.tar.gz
          #   skip_tests: true
          # - os_name: Linux-powerpc64le
          #   os: ubuntu-20.04
          #   target: powerpc64le-unknown-linux-gnu
          #   bin: dns-forward-over-tcp
          #   name: dns-forward-over-tcp-Linux-powerpc64le.tar.gz
          #   skip_tests: true
          # - os_name: Linux-riscv64
          #   os: ubuntu-20.04
          #   target: riscv64gc-unknown-linux-gnu
          #   bin: dns-forward-over-tcp
          #   name: dns-forward-over-tcp-Linux-riscv64gc-gnu.tar.gz
          # - os_name: Linux-s390x
          #   os: ubuntu-20.04
          #   target: s390x-unknown-linux-gnu
          #   bin: dns-forward-over-tcp
          #   name: dns-forward-over-tcp-Linux-s390x-gnu.tar.gz
          #   skip_tests: true
          # - os_name: NetBSD-x86_64
          #   os: ubuntu-20.04
          #   target: x86_64-unknown-netbsd
          #   bin: dns-forward-over-tcp
          #   name: dns-forward-over-tcp-NetBSD-x86_64.tar.gz
          #   skip_tests: true
          # - os_name: Windows-aarch64
          #   os: windows-latest
          #   target: aarch64-pc-windows-msvc
          #   bin: dns-forward-over-tcp.exe
          #   name: dns-forward-over-tcp-Windows-aarch64.zip
          #   skip_tests: true
          # - os_name: Windows-i686
          #   os: windows-latest
          #   target: i686-pc-windows-msvc
          #   bin: dns-forward-over-tcp.exe
          #   name: dns-forward-over-tcp-Windows-i686.zip
          #   skip_tests: true
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: dns-forward-over-tcp.exe
            name: dns-forward-over-tcp-Windows-x86_64.zip
          - os_name: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: dns-forward-over-tcp
            name: dns-forward-over-tcp-Darwin-x86_64.tar.gz
          - os_name: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: dns-forward-over-tcp
            name: dns-forward-over-tcp-Darwin-aarch64.tar.gz
            skip_tests: true
          # - os_name: Linux-aarch64
          #   os: ubuntu-20.04
          #   target: aarch64-unknown-linux-musl
          #   bin: dns-forward-over-tcp
          #   name: dns-forward-over-tcp-aarch64-musl.tar.gz
          # - os_name: Windows-x86_64
          #   os: windows-latest
          #   target: x86_64-pc-windows-msvc
          #   bin: dns-forward-over-tcp.exe
          #   name: dns-forward-over-tcp-x86_64.zip
          #   skip_tests: true
        toolchain:
          - stable
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      # - name: Run tests
      #   uses: houseabsolute/actions-rust-cross@v0
      #   with:
      #     command: "test"
      #     target: ${{ matrix.platform.target }}
      #     toolchain: ${{ matrix.toolchain }}
      #     args: "--locked --release"
      #   if: ${{ !matrix.platform.skip_tests }}
      - name: Package as archive
        shell: bash
        run: |
          cd target/${{ matrix.platform.target }}/release
          if [[ "${{ matrix.platform.os }}" == "windows-latest" ]]; then
            7z a ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }}
          else
            tar czvf ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }}
          fi
          cd -
        # if: |
        #   matrix.toolchain == 'stable' &&
        #   ( startsWith( github.ref, 'refs/tags/v' ) ||
        #     github.ref == 'refs/tags/test-release' )
      - name: Publish release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dns-forward-over-tcp-${{ matrix.platform.os_name }}
          path: "dns-forward-over-tcp-*"
      #   # if: matrix.toolchain == 'stable' && github.ref == 'refs/tags/test-release'
      - name: Generate SHA-256
        run: shasum -a 256 ${{ matrix.platform.name }}
        # if: |
        #   matrix.toolchain == 'stable' &&
        #   matrix.platform.os == 'macOS-latest' &&
        #   ( startsWith( github.ref, 'refs/tags/v' ) ||
        #     github.ref == 'refs/tags/test-release' )
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: "dns-forward-over-tcp-*"
          #body_path: Changes.md
        if: matrix.toolchain == 'stable' && startsWith( github.ref, 'refs/tags/v' )
